name: fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  badges: ^3.1.2
  bottom_navy_bar: ^6.1.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
